import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-houserenovation',
  templateUrl: './houserenovation.component.html',
  styleUrls: ['./houserenovation.component.css']
})
export class HouserenovationComponent implements OnInit {
  i1:any="../../../../assets/r3.webp";
  public h1:any="HOUSE RENOVATION";
  public h2:any="Renovation (also called remodeling) is the process of improving a broken, damaged, or outdated structure. Renovations are typically either commercial or residential. Additionally, renovation can refer to making something new, or bringing something back to life and can apply in social contexts. For example, a community can be renovated if it is strengthened and revived.";
  public p1:any="1. Finishes- Technology has had a meaningful impact on the renovation process, increasing the significance and strength of the planning stage. The availability of free online design tools has improved visualization of the changes, at a fraction of the cost of hiring a professional interior designer. The decision regarding changes is also influenced by the purpose of renovation. In case of a so-called  repair and resell objective, an ROI return on investment can result from changes to fix a structural issue or design flow yield[1] or to use light and color to make rooms appear more spacious.";
  public p2:any="2. Reasons- Many cities and towns have been renovated because of the devastations, such as Rovaniemi in Lapland, Finland.[2] Video about the post-war era reconstruction of Rovaniemi in 1949.Many people renovate homes to create a new appearance. Builders may renovate homes to enhance the home's value as a stable source of income.[3] Homeowners often renovate their homes to increase the re-sale value and to turn a profit when selling. Homeowners may also want to add renovations that make their home more energy efficient, green or sustainable.[4] Or simply, over time, a homeowners personal preferences and needs may change, and the home will be renovated for improved aesthetics, comfort, or functionality.";
  public p3:any="3.Wood and renovations- Wood is versatile and flexible, making it the easiest construction material for renovations, and wood buildings can be redesigned to suit changing needs. Few homeowners or professional remodellers possess the skill and equipment that is required to alter steel-frame or concrete structures.Forest certification verifies that wood products have been sourced from well-managed forests. Most certification programs provide online search options so that consumers can find certified products—the Certification Canada program includes a search option for all of the certification programs that are in use in Canada.[5]In North America, most structures are demolished because of external forces such as zoning changes and rising land values. Additionally, buildings that cannot be modified to serve the functional needs of the occupants are subject to demolition. Very few buildings on the continent are demolished due to structural degradation.[6]The Athena Institute surveyed 227 commercial and residential buildings that were demolished in St. Paul, Minnesota, between 2000 and mid-2003. Thirty percent of the buildings were less than 50 years old, and 6% were less than 25 years old. The four top reasons for demolition were “area redevelopment” (35%), “building’s physical condition” (31%), “not suitable for anticipated use” (22%), and “fire damage” (7%). Lack of maintenance was cited as the specific problem for 54 of the 70 buildings where physical condition was given as the reason for demolition.[6]";
  public p4:any="1. Renovation- Most builders focus on building new homes, so renovating is typically a part-time activity for such tradespeople. The processes and services required for renovations are quite specific and, once plans are signed off, building a new home is relatively predictable. Renovations usually require all of the sub-trades that are needed for the construction of a new building. During renovation projects, flexibility is often required from renovation companies to respond to unexpected issues that arise. Projects involving renovation require not just flexibility, but a plan that had been agreed upon by multiple parties. The planning process will involve feedback from financial investors of the project, and from the designer. Part of planning will also entail the collection of data for the completion of the project and then the project plan will be revised and given consent before continuing with renovations.[7]";
  public l1:any="Process";
  public   :any="";
  constructor() { }

  ngOnInit(): void {
  }

}
